resources:
  repositories:
  - repository: zhc
    type: github
    endpoint: Koenkk
    name: Koenkk/zigbee-herdsman-converters

trigger: none

pool:
  vmImage: 'ubuntu-latest'


steps:
- checkout: self
- checkout: zhc
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
- bash: |
    git config --global user.email "koenkanters94@gmail.com"
    git config --global user.name "Zigbee-herdsman-converters Bot"
    git config --global push.followTags true
    cd zigbee-herdsman-converters && export ZHC_VERSION=$(npm version patch)
    echo "New version $ZHC_VERSION"
    git push
    sleep 2m
    cd ../zigbee2mqtt
    npm install zigbee-herdsman-converters@${ZHC_VERSION:1} --save --save-exact
    rm -rf node_modules npm_shrinkwrap.json 
    npm install
    npm shrinkwrap --dev
    git push