resources:
  repositories:
  - repository: zhc
    type: github
    endpoint: Koenkk
    name: Koenkk/zigbee-herdsman-converters

trigger: none

pool:
  vmImage: 'ubuntu-latest'


steps:
- checkout: self
- checkout: zhc
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'
- bash: git config --global user.email "koenkanters94@gmail.com" && git config --global user.name "Zigbee-herdsman-converters Bot"
- bash: cd zigbee-herdsman-converters && export ZHC_VERSION=$(npm version patch)
- bash: |
    cd zigbee2mqtt && sed -i -E 's/.*"zigbee-herdsman-converters".*/\    "zigbee-herdsman-converters": "$ZHC_VERSION"/' package.json
- bash: cat zigbee2mqtt/package.json