resources:
  repositories:
  - repository: zhc
    type: github
    endpoint: MyGitHubServiceConnection
    name: Koenkk/zigbee-herdsman-converters

trigger: none

pool:
  vmImage: 'ubuntu-latest'


steps:
- checkout: self
- checkout: zhc

- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'


